language: python
python:
- "3.5"
# command to install dependencies
install:
- pip install -r requirements.txt
- pip install coveralls pytest pytest-cov

script:
- pytest --cov=coapthon
after_success:
- coveralls